src/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SMS_Keys__c</fullName>
        <label>SMS Keys</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EventDecorator.cls
global class EventDecorator {

    global Long externalId {get; set;}
    global DateTime startTime {get; set;}
    global String location {get; set;}
    global String name {get; set;}
    global String smsKeys {get; set;}

    global EventDecorator(Event__c rec)
    {
		externalId = Long.valueOf(rec.External_ID__c);
		startTime = rec.Start_Time__c;
		location = rec.Location__c;
		name = rec.Name;
		smsKeys = rec.SMS_Keys__c;
    }
}