src/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SMS_Keys__c</fullName>
        <label>SMS Keys</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EventEndpointController.cls
@RestResource(urlMapping='/events/*')
global class EventEndpointController
{
    @HttpGet
    global static void getEvents()
    {   
        
        List<Event__c> events = [SELECT Name, Start_Time__c, SMS_Keys__c, Location__c, External_ID__c FROM Event__c];
        List<EventDecorator> decorators = new List<EventDecorator>();
        for (Event__c event: events)
        {
            decorators.add(new EventDecorator(event));
        }
        
        RestContext.response.addHeader('Content-Type', 'application/json');
        RestContext.response.responseBody = Blob.valueOf(JSON.serialize(decorators));
    }
    
    global class Result
    {
        global String response {get; set;}
    }
}