src/objects/SMS_Message__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>160</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>From_Number__c</fullName>
        <label>From Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>To_Number__c</fullName>
        <label>To Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Incoming</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outgoing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SMS Message</label>
    <nameField>
        <displayFormat>SMS-{000000}</displayFormat>
        <label>SMS Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TextMessageSender.cls
public with sharing class TextMessageSender 
{

    public static final String TWILIO_NUMBER = '+13043978075';
    
    public static void send(Set<String> toNumbers, String message)
    {
        TwilioRestClient client = TwilioAPI.getDefaultClient();

        try 
        {
            //Map<String,String> params = new Map<String,String> {
            //    'To'   => '+16232526671',
            //    'From' => TWILIO_NUMBER,
            //    'Body' => 'Hello there!'
            //};
            ////TwilioSMSList smss = client.getAccount().getSMSMessages(); 
            
            //for (Integer i = 0; i < 11; i++)
            //{
            //    String oldBody = params.get('Body');
            //    String newBody = oldBody.substring(0, oldBody.length() - 2);
            //    newBody += i;
            //    params.put('Body', newBody);
            //    TwilioSMS sms = client.getAccount().getSMSMessages().create(params);    
            //}
            List<SMS_Message__c> messages = new List<SMS_Message__c>();

            for (String toNumber : toNumbers)
            {
                SMS_Message__c sms = new SMS_Message__c();
                sms.From_Number__c = TWILIO_NUMBER;
                sms.To_Number__c = toNumber;
                sms.Body__c = message;
                sms.Type__c = 'Outgoing';
                sms.Sent__c = false;
                messages.add(sms);
            }

            insert messages;
            MassTextMessageSender sender = new MassTextMessageSender();
            Id batchprocessid = Database.executebatch(sender,1);
            System.debug('###batchprocessid: ' + batchprocessid);

        }
        catch (Exception e)
        {
            System.debug('###' + e);
        }
    }

}